pipeline  { 
    agent any 
    environment { 
        DOCKER_CREADS = credentials('docker-hub-login')
        IMAGE_TAG = "v${BUILD_NUMBER}"
    }
    stages { 
        stage('Build & Push Docker') { 
            steps { 
                git url : 'https://github.com/shieldx-bot/backend_exemple.git', branch: 'main' 

                sh 'npm install ' 
                sh "docker build -t shieldxbot/backend_exemple:${IMAGE_TAG} ."
                
                 
                sh '''
                 echo "$DOCKER_CREADS_PSW" | docker login -u "$DOCKER_CREADS_USR" --password-stdin
                    '''

                sh "docker push shieldxbot/backend_exemple:${IMAGE_TAG}"
                
                           
                }
                
        }
        stage('Deploy to Kubernetes') { 
            steps { 
                withKubeConfig([credentialsId: 'k8s-kubeconfig']) { 
                    sh "sed -i 's/Docker_Image_Tag/${IMAGE_TAG}/g' ./k8s/deployment.yaml"
                    sh 'cat ./k8s/deployment.yaml'
                    sh 'kubectl  apply -f ./k8s/deployment.yaml'
                    sh 'kubectl rollout status  deployment/backend-exemple-deployment'
                }
            }
        }
    }
}