pipeline {
    agent any
    environment{
        // Nếu 'docker-hub-login' là username/password credential, Jenkins sẽ tạo:
        // DOCKER_HUB_USR và DOCKER_HUB_PSW
        DOCKER_HUB = credentials('docker-hub-login')
        // Nếu telegram token/chat id là secret text, thì biến sẽ chứa giá trị trực tiếp
        TELEGRAM_TOKEN = credentials('telegram-bot-token')
        TELEGRAM_CHAT_ID = credentials('telegram-chat-id')
        image_name = 'shieldxbot/backend_exemple'
        image_tag = "v${BUILD_NUMBER}-${BRANCH_NAME}"
    }
    stages{

        
       stage("Update Manifest (GitOps)") {
            when {
                branch 'main'
            }
            steps {
                script {
    env.IMAGE_TAG = "v${env.BUILD_NUMBER}-${env.BRANCH_NAME ?: 'main'}"
}

                dir('backend_exemple') {
                    script {
                        // 1. Dùng SED để sửa file Deployment.yaml (thay tag ảnh mới)
                        sh "sed -i 's|Docker_version|${env.IMAGE_TAG}|g' ./step2/k8s/Deployment.yaml"
                        
                        // 2. Commit và Push lên GitHub
                        withCredentials([usernamePassword(credentialsId: 'git-credentials', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                            sh """
                                git config user.email "jenkins-bot@shieldx.local"
                                git config user.name "Jenkins Bot"
                                
                                // Add file đã sửa
                                git add ./step2/k8s/Deployment.yaml
                                
                                // Commit
                                git commit -m "Deploy: Update version to ${env.IMAGE_TAG}"
                                
                                // Push (Dùng token để xác thực)
                                git push https://${GIT_USER}:${GIT_PASS}@github.com/shieldx-bot/Learn_Jenkins.git HEAD:main
                            """
                        }
                    }
                }
            }
        }


        
    } 
    post {
        success {
            NotifyTelegram("SUCCEEDED")
        }
        failure {
            NotifyTelegram("FAILED")
        }
    }
}


def NotifyTelegram(String status) {
    def msg = "Jenkins Pipeline ${status} for ${JOB_NAME} - Build #${BUILD_NUMBER} \nCheck details at: ${BUILD_URL}"
    sh '''curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=''' + msg + '''" '''
}