pipeline{
    agent any
    environment{ 
        DOCKER_CREADS = credentials('docker-hub-login')
        image_name = 'shieldxbot/backend_exemple'
        image_tag = "v${BUILD_NUMBER}-${BRANCH_NAME}"
        TELEGRAM_TOKEN = credentials('telegram-bot-token')
        TELEGRAM_CHAT_ID = credentials('telegram-chat-id')
    }
    stages{

        stage("Clean Workspace"){
            steps{
                cleanWs()
            }
            
        }

        stage("Git Clone Repository and Run Tests"){ 
            when { 
                anyOf { 
                    branch 'main'
                    branch 'dev'
                }
            }
            steps { 
                dir('backend_exemple')  { 
                    git url: 'https://github.com/shieldx-bot/Learn_Jenkins.git' , branch:'main'
                    sh 'cd ./step2/backend2 && npm install'
                    
                }
            }
             
        }
        stage("Build Docker Image") {
            when { 
               ` anyOf { 
                    branch 'main'
                    branch 'dev'
                }
            }
            steps { 
                dir('backend_exemple')  { 
                  sh "echo ${DOCKER_CREADS_PSW} | docker login -u $DOCKER_CREADS_USR --password-stdin"
                  sh "cd ./step2/backend2 && docker build -t ${image_name}:${image_tag} ."
                  sh "docker push ${image_name}:${image_tag}"

                }
            }
             
        }
        stage("Deploy Docker Image to Microk8s") {
            when { 
                branch 'main'
            }
            steps {
                 dir('backend_exemple') { 
                    withKubeConfig([credentialsId : 'kubeconfig-jenkins']) { 
                        sh "sed -i 's|Docker_version|${image_tag}|g' ./step2/k8s/Deployment.yaml"
                        sh 'cat ./step2/k8s/Deployment.yaml'
                        sh 'microk8s kubectl apply -f ./step2/k8s/Deployment.yaml'
                        sh 'microk8s kubectl get pods'
                        sh 'microk8s kubectl rollout status deployment.apps/step2-backend-deployment'
                    }
                 }
            }
            
        }
    
        
    }
    post{
        always{
            echo "========always========"
        }
        success{
             notifyTelegram("Jenkins Pipeline Succeeded for ${JOB_NAME} - Build #${BUILD_NUMBER} \n Check details at: ${BUILD_URL}")
            echo "========pipeline executed successfully========"
        }
        failure{
                notifyTelegram("Jenkins Pipeline Failed for ${JOB_NAME} - Build #${BUILD_NUMBER} \n Check details at: ${BUILD_URL}")
                echo "========pipeline execution failed========"
            
         }
    }
}

def notifyTelegram(String message){ 
    sh "curl  -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text='${message}'"
}